django-blog/blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('blog/', include('blogapp.urls'))
]

django-blog/blog/blogapp/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.create, name='create'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.register, name='register'),
    path('<title>', views.detail, name='detail')
]

django-blog/blog/blogapp/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User

# Create your models here.


class Post(models.Model):
    body = models.TextField()
    timestamp = models.DateTimeField(default=datetime.now)
    title = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Comment(models.Model):
    body = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(default=datetime.now)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.body

django-blog/blog/blogapp/forms.py
from django import forms
from . import models


class CreatePost(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['title', 'body']


class CreateComment(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ['body']

django-blog/blog/blogapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required

# Create your views here.
from .models import Post, Comment
from . import forms


def index(request):
    context = {'posts': Post.objects.all()}
    return render(request, 'blogapp/index.html', context)


def detail(request, title):
    post = Post.objects.get(title=title)
    if request.method == 'POST':
        form = forms.CreateComment(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.post = post
            instance.user = request.user
            instance.save()
            return redirect('blog:detail', title)
    else:
        comments = Comment.objects.filter(post=post).order_by('-timestamp')
        form = forms.CreateComment()
        context = {'post': post, 'comments': comments, 'form': form}
        return render(request, 'blogapp/detail.html', context)


@login_required
def create(request):
    if request.method == 'POST':
        form = forms.CreatePost(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            return HttpResponseRedirect(reverse('blog:index'))
    else:
        form = forms.CreatePost()
        return render(request, 'blogapp/create.html', {'form': form})


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return HttpResponseRedirect(reverse('blog:index'))
    else:
        form = UserCreationForm()
        return render(request, 'blogapp/register.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return HttpResponseRedirect(reverse('blog:index'))
    else:
        form = AuthenticationForm()
        return render(request, 'blogapp/login.html', {'form': form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return HttpResponseRedirect(reverse('blog:login'))

django-blog/blog/blogapp/templates/blogapp/create.html
{% extends "base.html" %} {% block content %}
<div>
  <form class="create-form" action="{% url 'blog:create' %}" method="POST">
    {% csrf_token %} {{ form }}
    <button type="submit">Post</button>
  </form>
</div>
{% endblock %}

django-blog/blog/blogapp/templates/blogapp/detail.html
{% extends "base.html" %} {% block content %}
<div>
  <h1 class="title">{{post.title}}</h1>
  <h4 class="meta">{{post.user}} - {{post.timestamp}}</h4>
  <p class="body">{{post.body}}</p>
  <ul class="comments">
    <form class="comments-form" action="{% url 'blog:detail' title=post.title %}" method="POST">
      {% csrf_token %} {{ form }}
      <button type="submit">Post</button>
    </form>
    {% for comment in comments %}
    <li>
      <p>{{comment.user}} - {{comment.timestamp}}</p>
      <p>{{comment.body}}</p>
    </li>
    {% endfor %}
  </ul>
</div>
{% endblock %}

django-blog/blog/blogapp/templates/blogapp/index.html
{% extends "base.html" %} {% block content %}
<div>
  <ul>
    {% for post in posts %}
    <li class="post">
      <h2>
        <a href="{% url 'blog:detail' title=post.title %}">{{post.title}}</a>
      </h2>
      <p>{{post.user}} - {{post.timestamp}}</p>
    </li>
    {% endfor %}
  </ul>
</div>
{% endblock %}

django-blog/blog/blogapp/templates/blogapp/login.html
{% extends "base.html" %} {% block content %}
<div>
  <form class="login-form" action="{% url 'blog:login' %}" method="POST">
    {% csrf_token %} {{ form }}
    <button>Login</button>
  </form>
</div>
{% endblock %}

django-blog/blog/blogapp/templates/blogapp/register.html
{% extends "base.html" %} {% block content %}
<div>
  <h1>Regsiter</h1>
  <form action="{% url 'blog:register' %}" method="POST">
    {% csrf_token %} {{ form }}
    <button>Regsiter</button>
  </form>
</div>
{% endblock %}

django-blog/blog/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Django Blog</title>
  {% load static %}

  <link rel="stylesheet" type="text/css" href="{% static 'blogapp/styles.css' %}" />
</head>

<body>
  <header>
    <nav>
      <ul class="links">
        {% if user.is_authenticated %}
        <li>
          <a class="link" href="create">New Post</a>
        </li>
        <li>
          <form action="{% url 'blog:logout' %}" method="POST">
            {% csrf_token %}
            <button class='link' type="submit">Logout</button>
          </form>
        </li>
        {% endif %}
      </ul>
    </nav>
  </header>
  {% block content %} {% endblock %}
</body>

</html>