url_shortener/url_shortener/url_shortener/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('url_shorten/', include('urlapp.urls'))
]

url_shortener/url_shortener/urlapp/urls.py
from django.urls import path
from . import views


app_name = 'urls'
urlpatterns = [
    path('', views.index, name='index'),
    path('save', views.save, name='save'),
    path('redirect/<code>', views.redirect, name='redirect')
]

url_shortener/url_shortener/urlapp/models.py
from django.db import models
from uuid import uuid4
from datetime import datetime

# Create your models here.


class Url(models.Model):
    code = models.UUIDField(default=uuid4, editable=False)
    created_date = models.DateTimeField(default=datetime.now())
    url = models.URLField()

    def __str__(self):
        return self.code

url_shortener/url_shortener/urlapp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.
from .models import Url


def index(request):
    context = {'urls': Url.objects.all().order_by('-created_date')[:5]}
    return render(request, 'urlapp/index.html', context)


def save(request):
    if request.method == 'POST':
        url = request.POST['url_input']
        new_url = Url(url=url)
        new_url.save()
        return HttpResponseRedirect(reverse('urls:index'))


def redirect(request, code):
    url = Url.objects.get(code=code)
    return HttpResponseRedirect(url.url)

url_shortener/url_shortener/urlapp/templates/urlapp/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Django Url Shortener</title>
  {% load static %}

  <link rel="stylesheet" type="text/css" href="{% static 'urlapp/style.css' %}" />
</head>

<body>
  <div>
    <form action="{% url 'urls:save' %}" method="POST">
      {% csrf_token %}
      <input name="url_input" type="text" placeholder="Enter a url to shorten">
      <button type="submit">Shorten</button>
    </form>
    <table>
      <tr>
        <th>Code</th>
        <th>Url</th>
        <th>Created</th>
      </tr>
      {% for url in urls %}
      <tr>
        <th>
          <a href="{% url 'urls:redirect' code=url.code %}">{{ url.code }}</a>
        </th>
        <th>{{ url.url }}</th>
        <th>{{ url.created_date }}</th>
      </tr>
      {% endfor %}
    </table>
  </div>
</body>

</html>