django-todos/todosite/todosapp/urls.py
from django.urls import path
from . import views


app_name = 'todos'
urlpatterns = [
    path('', views.index, name="index"),
    path('add', views.add, name="add"),
    path('complete', views.complete, name="complete"),
    path('delete', views.delete, name="delete")
]

django-todos/todosite/todosite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('todos/', include('todosapp.urls')),
    path('admin/', admin.site.urls),
]

django-todos/todosite/todosapp/models.py
from django.db import models
from datetime import datetime
# Create your models here.


class Todo(models.Model):
    todo_text = models.CharField(max_length=250, unique=True)
    created_date = models.DateTimeField(default=datetime.now())
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.todo_text

django-todos/todosite/todosapp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Todo


def index(request):
    context = {'todos': Todo.objects.all().order_by('-created_date')[:5]}
    return render(request, 'todosapp/index.html', context)


def add(request):
    if request.method == 'POST':
        todo_text = request.POST['todoInput']
        new_todo = Todo(todo_text=todo_text)
        new_todo.save()
        return HttpResponseRedirect(reverse('todos:index'))


def complete(request):
    if request.method == 'POST':
        todo_text = request.POST['todo']
        selected_todo = Todo.objects.get(todo_text=todo_text)
        if selected_todo.completed:
            selected_todo.completed = False
        else:
            selected_todo.completed = True
        selected_todo.save()
    return HttpResponseRedirect(reverse('todos:index'))


def delete(request):
    if request.method == 'POST':
        todo_text = request.POST['todo']
        selected_todo = Todo.objects.get(todo_text=todo_text)
        selected_todo.delete()
    return HttpResponseRedirect(reverse('todos:index'))

django-todos/todosite/todosapp/templates/todosapp/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>

<body>
  <div>
    <form action="{% url 'todos:add' %}" method="POST">
      {% csrf_token %}
      <input name="todoInput" type="text" placeholder="Enter a todo">
      <button type="submit">Add</button>
    </form>
    <ul>
      {% for todo in todos %}
      <li>
        <p>{{ todo.todo_text }}</p>
        <p>Completed {{ todo.completed }}</p>
        <p>Created on {{ todo.created_date }}</p>
        <form action="{% url 'todos:complete' %}" method="POST">
          {% csrf_token %}
          <input type="hidden" name="todo" value="{{ todo.todo_text }}">
          <button type="submit">Complete</button>
        </form>
        <form action="{% url 'todos:delete' %}" method="POST">
          {% csrf_token %}
          <input type="hidden" name="todo" value="{{ todo.todo_text }}">
          <button type="submit">Delete</button>
        </form>
      </li>
      {% endfor %}
    </ul>
  </div>
</body>

</html>